// Generated by CoffeeScript 1.6.2
(function() {
  var DeepPropertyWatcher, dref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  dref = require("dref");

  module.exports = DeepPropertyWatcher = (function() {
    /*
    */
    function DeepPropertyWatcher(target, property, callback) {
      this.target = target;
      this.property = property;
      this.callback = callback;
      this.changed = __bind(this.changed, this);
      this._chain = property.split(".");
      this._watch();
    }

    /*
    */


    DeepPropertyWatcher.prototype.dispose = function() {
      var listener, _i, _len, _ref;

      if (this._listeners) {
        _ref = this._listeners;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          listener = _ref[_i];
          listener.dispose();
        }
        return this._listeners = void 0;
      }
    };

    /*
    */


    DeepPropertyWatcher.prototype._watch = function() {
      var i, part, property, value, _i, _len, _ref, _results,
        _this = this;

      if (this._listeners) {
        this.dispose();
      }
      this._listeners = [];
      _ref = this._chain;
      _results = [];
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        part = _ref[i];
        property = this._chain.slice(0, i + 1).join(".");
        value = this.target.get(property);
        if (value && value.__isBindable) {
          _results.push(this._listeners.push(new DeepPropertyWatcher(value, this._chain.slice(i + 1).join("."), this.changed)));
        } else {
          _results.push(this._listeners.push(this.target.on("change:" + property, function() {
            return _this.changed();
          })));
        }
      }
      return _results;
    };

    /*
    */


    DeepPropertyWatcher.prototype.changed = function() {
      this.callback();
      return this._watch();
    };

    return DeepPropertyWatcher;

  })();

}).call(this);
