// Generated by CoffeeScript 1.6.2
(function() {
  exports.get = function(target, key, flatten) {
    var ct, i, k, keyParts, _i, _len;

    if (flatten == null) {
      flatten = true;
    }
    if (!target) {
      return;
    }
    keyParts = key ? key.split(".") : [];
    ct = target;
    for (i = _i = 0, _len = keyParts.length; _i < _len; i = ++_i) {
      k = keyParts[i];
      if (!ct) {
        return;
      }
      if (ct.__isBindable) {
        return ct.get(keyParts.slice(i).join("."));
      }
      ct = ct[k];
    }
    if (flatten && ct && ct.__isBindable) {
      return ct.get();
    }
    return ct;
  };

  exports.set = function(target, key, value) {
    var ct, firstKey, i, k, keyParts, n, nv, _i, _len, _ref;

    if (!target || !key) {
      return;
    }
    keyParts = key.split(".");
    firstKey = keyParts.shift();
    if (!(ct = target[firstKey]) || firstKey === "data" || target.data[firstKey]) {
      ct = target.data;
      keyParts.unshift(firstKey);
    }
    n = keyParts.length;
    for (i = _i = 0, _len = keyParts.length; _i < _len; i = ++_i) {
      k = keyParts[i];
      if (ct.__isBindable) {
        ct.set(keyParts.slice(i).join("."), value);
        return;
      } else {
        if (i === n - 1) {
          ct[k] = value;
          break;
        } else {
          nv = ct[k] || ((_ref = ct.data) != null ? _ref[k] : void 0);
          if (!nv || (typeof nv !== "object")) {
            nv = ct[k] = {};
          }
          ct = nv;
        }
      }
    }
  };

}).call(this);
