// Generated by CoffeeScript 1.6.3
(function() {
  exports.get = function(bindable, context, keyParts, flatten) {
    var ct, i, k, _i, _len;
    if (flatten == null) {
      flatten = true;
    }
    if (!context) {
      return context;
    }
    if (!keyParts) {
      keyParts = [];
    }
    if (typeof keyParts === "string") {
      keyParts = keyParts.split(".");
    }
    ct = context;
    for (i = _i = 0, _len = keyParts.length; _i < _len; i = ++_i) {
      k = keyParts[i];
      if (!ct) {
        return;
      }
      if (ct.__isBindable && ct !== bindable) {
        return ct.get(keyParts.slice(i).join("."));
      }
      ct = ct[k];
    }
    if (flatten && ct && ct.__isBindable) {
      return ct.get();
    }
    return ct;
  };

  exports.set = function(bindable, key, value) {
    var ct, i, k, keyParts, n, nv, _i, _len;
    keyParts = key.split(".");
    n = keyParts.length;
    ct = bindable.__context;
    for (i = _i = 0, _len = keyParts.length; _i < _len; i = ++_i) {
      k = keyParts[i];
      if (ct.__isBindable && ct !== bindable) {
        return ct.set(keyParts.slice(i).join("."), value);
      } else {
        if (i === n - 1) {
          if (ct[k] === value) {
            return false;
          }
          ct[k] = value;
          return true;
        } else {
          nv = ct[k];
          if (!nv || (typeof nv !== "object")) {
            nv = ct[k] = {};
          }
          ct = nv;
        }
      }
    }
  };

}).call(this);
