// Generated by CoffeeScript 1.6.2
(function() {
  var Bindable, Binding, Builder, EventEmitter, dref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  dref = require("dref");

  EventEmitter = require("../core/eventEmitter");

  Binding = require("./binding");

  Builder = require("../core/builder");

  dref.use(require("../shim/dref"));

  module.exports = Bindable = (function(_super) {
    __extends(Bindable, _super);

    /*
    */


    Bindable.prototype.__isBindable = true;

    /*
    */


    function Bindable(data) {
      var key, obj;

      Bindable.__super__.constructor.call(this);
      this._initData(data);
      this._bindings = [];
      for (key in this) {
        obj = this[key];
        if (obj && obj.__isCallChain) {
          this[key] = void 0;
          obj.createObject(this, key);
        }
      }
    }

    /*
    */


    Bindable.prototype._initData = function(data) {
      this.data = data != null ? data : {};
    };

    /*
    */


    Bindable.prototype.get = function(key) {
      var result;

      result = this._ref(this.data, key);
      if ((result === null) || (result === void 0)) {
        result = this._ref(this, key);
      }
      return result;
    };

    /*
    */


    Bindable.prototype.has = function(key) {
      return !!this.get(key);
    };

    /*
    */


    Bindable.prototype.set = function(key, value) {
      var k;

      if (arguments.length === 1) {
        for (k in key) {
          this.set(k, key[k]);
        }
        return;
      }
      if (value && value.__isBinding) {
        value.to(this, key);
        return;
      }
      return this._set(key, value);
    };

    /*
    */


    Bindable.prototype._set = function(key, value) {
      dref.set(this.data, key, value);
      this.emit("change:" + key, value);
      this.emit("change", value);
      return this;
    };

    /*
    */


    Bindable.prototype._ref = function(context, key) {
      if (!key) {
        return context;
      }
      return dref.get(context, key);
    };

    /*
    */


    Bindable.prototype.bind = function(property, to) {
      if (to && to.__isBinding) {
        this.set(property, to);
        return;
      }
      return new Binding(this, property).to(to);
    };

    /*
    */


    Bindable.prototype.dispose = function() {
      return this.emit("dispose");
    };

    return Bindable;

  })(EventEmitter);

  new Builder(Binding, Bindable);

  module.exports.EventEmitter = EventEmitter;

}).call(this);
