// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = {
    test: function(item) {
      return item.get && item.set;
    },
    get: function(item, key) {
      return item.data[key] || item[key];
    },
    set: function(item, key, value) {
      return item.set(key, value);
    }
  };

}).call(this);
