// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = {
    test: function(item) {
      return item.get && item.set;
    },
    get: function(item, key) {
      var result;

      result = item.data[key];
      if ((result === null) || (result === void 0)) {
        result = item[key];
      }
      return result;
    },
    set: function(item, key, value) {
      return item.set(key, value);
    }
  };

}).call(this);
