// Generated by CoffeeScript 1.6.2
(function() {
  exports.Object = require("./object");

  exports.Collection = require("./collection");

  exports.EventEmitter = require("./core/eventEmitter");

}).call(this);
