// Generated by CoffeeScript 1.6.2
(function() {
  var hoist;

  hoist = require("hoist");

  exports.tryTransform = function(transformer, method, value, callback) {
    if (!transformer) {
      return callback(null, value);
    }
    return transformer[method].call(transformer, value, callback);
  };

  exports.transformer = function(options) {
    if (typeof options === "function") {
      options = {
        from: options,
        to: options
      };
    }
    if (!options.from) {
      options.from = function(value) {
        return value;
      };
    }
    if (!options.to) {
      options.to = function(value) {
        return value;
      };
    }
    return {
      from: hoist.map(options.from),
      to: hoist.map(options.to)
    };
  };

}).call(this);
