// Generated by CoffeeScript 1.6.3
(function() {
  var hoist;

  hoist = require("hoist");

  exports.tryTransform = function(transformer, method, value) {
    if (!transformer) {
      return value[0];
    }
    return transformer[method].call(transformer, value);
  };

  exports.transformer = function(options) {
    if (typeof options === "function") {
      options = {
        from: options,
        to: options
      };
    }
    if (!options.from) {
      options.from = function(value) {
        return value;
      };
    }
    if (!options.to) {
      options.to = function(value) {
        return value;
      };
    }
    return options;
  };

}).call(this);
