// Generated by CoffeeScript 1.6.2
(function() {
  var toarray;

  toarray = require("toarray");

  module.exports = function(properties, fn) {
    properties = toarray(properties);
    fn.refs = properties;
    return fn;
  };

}).call(this);
