// Generated by CoffeeScript 1.6.2
(function() {
  var async, utils;

  utils = require("../../core/utils");

  async = require("async");

  module.exports = (function() {
    /*
    */
    function _Class(binding, target) {
      this.binding = binding;
      this.target = target;
      this.init();
    }

    /*
    */


    _Class.prototype.init = function() {};

    /*
    */


    _Class.prototype.now = function() {};

    /*
    */


    _Class.prototype.dispose = function() {};

    /*
    */


    _Class.prototype.change = function(event, item, oldItem) {
      if (event === "reset") {
        return this._changeItems(event, item, oldItem);
      } else {
        return this._changeItem(event, item, oldItem);
      }
    };

    /*
    */


    _Class.prototype._changeItem = function(event, item, oldItem) {
      return this._change(event, item, oldItem);
    };

    /*
    */


    _Class.prototype._changeItems = function(event, items, oldItems) {
      /*
      if @_filter
        changed = items.filter @_filter
      else
        changed = items.concat()
      
      for item, i in changed
        changed[i] = @__transform "to", item
      
      @_change events, changed, oldItems
      */

    };

    /*
    */


    _Class.prototype._change = function(event, item) {};

    /*
    */


    _Class.prototype.bothWays = function() {};

    /*
    */


    _Class.prototype.__transform = function(method, value) {
      return utils.tryTransform(this._transformer, method, [value]);
    };

    return _Class;

  })();

}).call(this);
