// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = (function(_super) {
    __extends(_Class, _super);

    function _Class() {
      _ref = _Class.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    _Class.prototype.init = function() {
      return _Class.__super__.init.call(this);
    };

    /*
    */


    _Class.prototype.now = function() {
      if (this._initialized) {
        return;
      }
      return this._initialized = true;
    };

    /*
    */


    _Class.prototype._change = function(method, item, oldItems) {
      return this.target(method, item, oldItems);
    };

    return _Class;

  })(require("./base"));

}).call(this);
