// Generated by CoffeeScript 1.6.2
(function() {
  var utils;

  utils = require("../../core/utils");

  module.exports = (function() {
    /*
    */
    function _Class(binding) {
      this.binding = binding;
    }

    /*
    */


    _Class.prototype.change = function(value) {
      var oldValue;

      if (this._value === value) {
        return;
      }
      oldValue = this._value;
      this._value = value;
      return this._change(value, oldValue);
    };

    /*
    */


    _Class.prototype.bothWays = function() {};

    /*
    */


    _Class.prototype._change = function(value) {};

    return _Class;

  })();

}).call(this);
