// Generated by CoffeeScript 1.6.2
(function() {
  var utils;

  utils = require("../../core/utils");

  module.exports = (function() {
    /*
    */
    function _Class(binding) {
      this.binding = binding;
      this._transformer = this.binding.transform();
    }

    /*
    */


    _Class.prototype.change = function(value) {
      var oldValue, transformedValue;

      transformedValue = this.__transform("to", value);
      if (this._value === transformedValue) {
        return;
      }
      oldValue = this._value;
      this._value = transformedValue;
      return this._change(transformedValue, oldValue);
    };

    /*
    */


    _Class.prototype.bothWays = function() {};

    /*
    */


    _Class.prototype._change = function(value) {};

    /*
    */


    _Class.prototype.__transform = function(method, value) {
      return utils.tryTransform(this._transformer, method, value);
    };

    return _Class;

  })();

}).call(this);
