// Generated by CoffeeScript 1.6.2
(function() {
  var Base,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require("./base");

  module.exports = (function(_super) {
    __extends(_Class, _super);

    /*
    */


    function _Class(binding, to, property) {
      this.binding = binding;
      this.to = to;
      this.property = property;
      _Class.__super__.constructor.call(this, this.binding);
    }

    /*
    */


    _Class.prototype._change = function(newValue) {
      return this.to.set(this.property, newValue);
    };

    /*
    */


    _Class.prototype.dispose = function() {
      var _ref;

      if ((_ref = this._bothWaysBinding) != null) {
        _ref.dispose();
      }
      return this._bothWaysBinding = this.binding = this.to = this.property = null;
    };

    /*
    */


    _Class.prototype.bothWays = function() {
      var _this = this;

      return this._bothWaysBinding = this.to.bind(this.property).to(function(value) {
        if (_this._value === value) {
          return;
        }
        return _this._changeFrom(value);
      });
    };

    /*
    */


    _Class.prototype._changeFrom = function(value) {
      return this.binding._from.set(this.binding._property, this._value = this.__transform("from", value));
    };

    return _Class;

  })(Base);

}).call(this);
