// Generated by CoffeeScript 1.6.2
(function() {
  var Base, type,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require("./base");

  type = require("type-component");

  module.exports = (function(_super) {
    __extends(_Class, _super);

    /*
    */


    function _Class(binding, to) {
      this.binding = binding;
      this.to = to;
      _Class.__super__.constructor.call(this, this.binding);
    }

    /*
    */


    _Class.prototype._change = function(newValue) {
      this._ignoreBothWays = true;
      this.to.set(newValue);
      return this._ignoreBothWays = false;
    };

    /*
    */


    _Class.prototype.dispose = function() {
      var _ref;

      if ((_ref = this._bothWaysBinding) != null) {
        _ref.dispose();
      }
      return this._bothWaysBinding = this.binding = this.to = this.properties = null;
    };

    return _Class;

  })(Base);

}).call(this);
