// Generated by CoffeeScript 1.6.3
(function() {
  var Base,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require("./base");

  module.exports = (function(_super) {
    __extends(_Class, _super);

    /*
    */


    function _Class(binding, to, property) {
      this.binding = binding;
      this.to = to;
      this.property = property;
      _Class.__super__.constructor.call(this, this.binding);
    }

    /*
    */


    _Class.prototype._change = function(newValue, oldValue) {
      return this.to.reset(newValue, oldValue);
    };

    /*
    */


    _Class.prototype.dispose = function() {
      return this.to.disposeSourceBinding();
    };

    return _Class;

  })(Base);

}).call(this);
