// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = (function() {
    /*
    */

    function _Class(binding) {
      this.binding = binding;
      this._transform = this.binding.transform();
      this.init();
    }

    /*
    */


    _Class.prototype.init = function() {
      return this.change(this.binding._from.get(this.binding._property));
    };

    /*
    */


    _Class.prototype.change = function(value) {
      var _this = this;
      if (this.currentValue === value) {
        return false;
      }
      this.__transform("to", value, function(err, transformedValue) {
        if (err) {
          throw err;
        }
        return _this._change(_this.currentValue = transformedValue);
      });
      return true;
    };

    /*
    */


    _Class.prototype.bothWays = function() {};

    /*
    */


    _Class.prototype._change = function(value) {};

    /*
    */


    _Class.prototype.__transform = function(method, value, next) {
      var transform, _ref;
      transform = (_ref = this._transform) != null ? _ref[method] : void 0;
      if (!transform) {
        return next(null, value);
      }
      if (transform.length === 1) {
        return next(null, transform(value));
      } else {
        return transform(value, next);
      }
    };

    return _Class;

  })();

}).call(this);
