// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = (function() {
    /*
    */

    function _Class(binding) {
      this.binding = binding;
      this.init();
    }

    /*
    */


    _Class.prototype.init = function() {
      return this.change(this.binding.from.get(this.binding.property));
    };

    /*
    */


    _Class.prototype.change = function(value) {
      if (this.currentValue === value) {
        return false;
      }
      this._change(this.currentValue = value);
      return true;
    };

    /*
    */


    _Class.prototype.bothWays = function() {};

    /*
    */


    _Class.prototype._change = function(value) {};

    return _Class;

  })();

}).call(this);
