// Generated by CoffeeScript 1.4.0
(function() {
  var Base,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require("./base");

  module.exports = (function(_super) {

    __extends(_Class, _super);

    /*
    */


    function _Class(binding, to, property) {
      this.binding = binding;
      this.to = to;
      this.property = property;
      _Class.__super__.constructor.call(this, this.binding);
    }

    /*
    */


    _Class.prototype._change = function(value) {
      return this.to.set(this.property, value);
    };

    /*
    */


    _Class.prototype.dispose = function() {
      if (!this._disposable) {
        return;
      }
      this._disposable.dispose();
      return this._disposable = this.binding = this.to = this.property = null;
    };

    /*
    */


    _Class.prototype.bothWays = function() {
      return this._disposable = this.to.bind(this.property).to(this.binding._from, this.binding._property);
    };

    return _Class;

  })(Base);

}).call(this);
