// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = (function() {
    /*
    */

    function _Class(_transform) {
      this._transform = _transform;
    }

    /*
    */


    _Class.prototype["default"] = function(value) {
      if (!arguments.length) {
        return this._defaultValue;
      }
      this._defaultValue = value;
      return this;
    };

    /*
    */


    _Class.prototype.set = function(value) {
      return this._transform(value || this._defaultValue);
    };

    return _Class;

  })();

}).call(this);
